/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo;

import jaco.mp3.player.MP3Player;
import java.io.File;

public class bgIntro extends javax.swing.JFrame {

    /**
     * Creates new form bgIntro
     * @throws java.lang.Exception
     */
    public bgIntro() throws Exception {
        initComponents();
        setTitle("CALL OF DUTY");
        setVisible(true);
        MP3Player player = new MP3Player(new File("D:\\OOP\\Defense_System\\Defense_System\\Call of Duty Mobile Song To another Level By Oh The Larceny.mp3"));
        player.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(639, 359));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("skip");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 330, 60, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP\\Defense_System\\Defense_System\\The Doggfather Arrives in Call of Duty_ Mobile.gif")); // NOI18N
        jLabel1.setText("wdrrrrrr");
        jLabel1.setMaximumSize(new java.awt.Dimension(639, 359));
        jLabel1.setMinimumSize(new java.awt.Dimension(639, 359));
        jLabel1.setPreferredSize(new java.awt.Dimension(639, 359));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 639, 359);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Observerble();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
